#ifndef TEST_QUERIES_H
#define TEST_QUERIES_H

#include <sstream>

static std::stringstream Query1() {
    std::stringstream stream;
    stream << "{\n";
    stream << "    \"base_requests\": [\n";
    stream << "        {\n";
    stream << "            \"is_roundtrip\": true,\n";
    stream << "            \"name\": \"297\",\n";
    stream << "            \"stops\": [\n";
    stream << "                \"Biryulyovo Zapadnoye\",\n";
    stream << "                \"Biryulyovo Tovarnaya\",\n";
    stream << "                \"Universam\",\n";
    stream << "                \"Biryulyovo Zapadnoye\"\n";
    stream << "            ],\n";
    stream << "            \"type\": \"Bus\"\n";
    stream << "        },\n";
    stream << "        {\n";
    stream << "            \"is_roundtrip\": false,\n";
    stream << "            \"name\": \"635\",\n";
    stream << "            \"stops\": [\n";
    stream << "                \"Biryulyovo Tovarnaya\",\n";
    stream << "                \"Universam\",\n";
    stream << "                \"Prazhskaya\"\n";
    stream << "            ],\n";
    stream << "            \"type\": \"Bus\"\n";
    stream << "        },\n";
    stream << "        {\n";
    stream << "            \"latitude\": 55.574371,\n";
    stream << "            \"longitude\": 37.6517,\n";
    stream << "            \"name\": \"Biryulyovo Zapadnoye\",\n";
    stream << "            \"road_distances\": {\n";
    stream << "                \"Biryulyovo Tovarnaya\": 2600\n";
    stream << "            },\n";
    stream << "            \"type\": \"Stop\"\n";
    stream << "        },\n";
    stream << "        {\n";
    stream << "            \"latitude\": 55.587655,\n";
    stream << "            \"longitude\": 37.645687,\n";
    stream << "            \"name\": \"Universam\",\n";
    stream << "            \"road_distances\": {\n";
    stream << "                \"Biryulyovo Tovarnaya\": 1380,\n";
    stream << "                \"Biryulyovo Zapadnoye\": 2500,\n";
    stream << "                \"Prazhskaya\": 4650\n";
    stream << "            },\n";
    stream << "            \"type\": \"Stop\"\n";
    stream << "        },\n";
    stream << "        {\n";
    stream << "            \"latitude\": 55.592028,\n";
    stream << "            \"longitude\": 37.653656,\n";
    stream << "            \"name\": \"Biryulyovo Tovarnaya\",\n";
    stream << "            \"road_distances\": {\n";
    stream << "                \"Universam\": 890\n";
    stream << "            },\n";
    stream << "            \"type\": \"Stop\"\n";
    stream << "        },\n";
    stream << "        {\n";
    stream << "            \"latitude\": 55.611717,\n";
    stream << "            \"longitude\": 37.603938,\n";
    stream << "            \"name\": \"Prazhskaya\",\n";
    stream << "            \"road_distances\": {},\n";
    stream << "            \"type\": \"Stop\"\n";
    stream << "        }\n";
    stream << "    ],\n";
    stream << "    \"render_settings\": {\n";
    stream << "        \"bus_label_font_size\": 20,\n";
    stream << "        \"bus_label_offset\": [\n";
    stream << "            7,\n";
    stream << "            15\n";
    stream << "        ],\n";
    stream << "        \"color_palette\": [\n";
    stream << "            \"green\",\n";
    stream << "            [\n";
    stream << "                255,\n";
    stream << "                160,\n";
    stream << "                0\n";
    stream << "            ],\n";
    stream << "            \"red\"\n";
    stream << "        ],\n";
    stream << "        \"height\": 200,\n";
    stream << "        \"line_width\": 14,\n";
    stream << "        \"padding\": 30,\n";
    stream << "        \"stop_label_font_size\": 20,\n";
    stream << "        \"stop_label_offset\": [\n";
    stream << "            7,\n";
    stream << "            -3\n";
    stream << "        ],\n";
    stream << "        \"stop_radius\": 5,\n";
    stream << "        \"underlayer_color\": [\n";
    stream << "            255,\n";
    stream << "            255,\n";
    stream << "            255,\n";
    stream << "            0.85\n";
    stream << "        ],\n";
    stream << "        \"underlayer_width\": 3,\n";
    stream << "        \"width\": 200\n";
    stream << "    },\n";
    stream << "    \"routing_settings\": {\n";
    stream << "        \"bus_velocity\": 40,\n";
    stream << "        \"bus_wait_time\": 6\n";
    stream << "    },\n";
    stream << "    \"stat_requests\": [\n";
    stream << "        {\n";
    stream << "            \"id\": 1,\n";
    stream << "            \"name\": \"297\",\n";
    stream << "            \"type\": \"Bus\"\n";
    stream << "        },\n";
    stream << "        {\n";
    stream << "            \"id\": 2,\n";
    stream << "            \"name\": \"635\",\n";
    stream << "            \"type\": \"Bus\"\n";
    stream << "        },\n";
    stream << "        {\n";
    stream << "            \"id\": 3,\n";
    stream << "            \"name\": \"Universam\",\n";
    stream << "            \"type\": \"Stop\"\n";
    stream << "        },\n";
    stream << "        {\n";
    stream << "            \"from\": \"Biryulyovo Zapadnoye\",\n";
    stream << "            \"id\": 4,\n";
    stream << "            \"to\": \"Universam\",\n";
    stream << "            \"type\": \"Route\"\n";
    stream << "        },\n";
    stream << "        {\n";
    stream << "            \"from\": \"Biryulyovo Zapadnoye\",\n";
    stream << "            \"id\": 5,\n";
    stream << "            \"to\": \"Prazhskaya\",\n";
    stream << "            \"type\": \"Route\"\n";
    stream << "        }\n";
    stream << "    ]\n";
    stream << "}\n";
    return stream;
}

static std::stringstream Query2() {
    std::stringstream stream;
    stream << "{\n";
    stream << "  \"base_requests\": [\n";
    stream << "      {\n";
    stream << "          \"is_roundtrip\": true,\n";
    stream << "          \"name\": \"297\",\n";
    stream << "          \"stops\": [\n";
    stream << "              \"Biryulyovo Zapadnoye\",\n";
    stream << "              \"Biryulyovo Tovarnaya\",\n";
    stream << "              \"Universam\",\n";
    stream << "              \"Biryusinka\",\n";
    stream << "              \"Apteka\",\n";
    stream << "              \"Biryulyovo Zapadnoye\"\n";
    stream << "          ],\n";
    stream << "          \"type\": \"Bus\"\n";
    stream << "      },\n";
    stream << "      {\n";
    stream << "          \"is_roundtrip\": false,\n";
    stream << "          \"name\": \"635\",\n";
    stream << "          \"stops\": [\n";
    stream << "              \"Biryulyovo Tovarnaya\",\n";
    stream << "              \"Universam\",\n";
    stream << "              \"Biryusinka\",\n";
    stream << "              \"TETs 26\",\n";
    stream << "              \"Pokrovskaya\",\n";
    stream << "              \"Prazhskaya\"\n";
    stream << "          ],\n";
    stream << "          \"type\": \"Bus\"\n";
    stream << "      },\n";
    stream << "      {\n";
    stream << "          \"is_roundtrip\": false,\n";
    stream << "          \"name\": \"828\",\n";
    stream << "          \"stops\": [\n";
    stream << "              \"Biryulyovo Zapadnoye\",\n";
    stream << "              \"TETs 26\",\n";
    stream << "              \"Biryusinka\",\n";
    stream << "              \"Universam\",\n";
    stream << "              \"Pokrovskaya\",\n";
    stream << "              \"Rossoshanskaya ulitsa\"\n";
    stream << "          ],\n";
    stream << "          \"type\": \"Bus\"\n";
    stream << "      },\n";
    stream << "      {\n";
    stream << "          \"latitude\": 55.574371,\n";
    stream << "          \"longitude\": 37.6517,\n";
    stream << "          \"name\": \"Biryulyovo Zapadnoye\",\n";
    stream << "          \"road_distances\": {\n";
    stream << "              \"Biryulyovo Tovarnaya\": 2600,\n";
    stream << "              \"TETs 26\": 1100\n";
    stream << "          },\n";
    stream << "          \"type\": \"Stop\"\n";
    stream << "      },\n";
    stream << "      {\n";
    stream << "          \"latitude\": 55.587655,\n";
    stream << "          \"longitude\": 37.645687,\n";
    stream << "          \"name\": \"Universam\",\n";
    stream << "          \"road_distances\": {\n";
    stream << "              \"Biryulyovo Tovarnaya\": 1380,\n";
    stream << "              \"Biryusinka\": 760,\n";
    stream << "              \"Pokrovskaya\": 2460\n";
    stream << "          },\n";
    stream << "          \"type\": \"Stop\"\n";
    stream << "      },\n";
    stream << "      {\n";
    stream << "          \"latitude\": 55.592028,\n";
    stream << "          \"longitude\": 37.653656,\n";
    stream << "          \"name\": \"Biryulyovo Tovarnaya\",\n";
    stream << "          \"road_distances\": {\n";
    stream << "              \"Universam\": 890\n";
    stream << "          },\n";
    stream << "          \"type\": \"Stop\"\n";
    stream << "      },\n";
    stream << "      {\n";
    stream << "          \"latitude\": 55.581065,\n";
    stream << "          \"longitude\": 37.64839,\n";
    stream << "          \"name\": \"Biryusinka\",\n";
    stream << "          \"road_distances\": {\n";
    stream << "              \"Apteka\": 210,\n";
    stream << "              \"TETs 26\": 400\n";
    stream << "          },\n";
    stream << "          \"type\": \"Stop\"\n";
    stream << "      },\n";
    stream << "      {\n";
    stream << "          \"latitude\": 55.580023,\n";
    stream << "          \"longitude\": 37.652296,\n";
    stream << "          \"name\": \"Apteka\",\n";
    stream << "          \"road_distances\": {\n";
    stream << "              \"Biryulyovo Zapadnoye\": 1420\n";
    stream << "          },\n";
    stream << "          \"type\": \"Stop\"\n";
    stream << "      },\n";
    stream << "      {\n";
    stream << "          \"latitude\": 55.580685,\n";
    stream << "          \"longitude\": 37.642258,\n";
    stream << "          \"name\": \"TETs 26\",\n";
    stream << "          \"road_distances\": {\n";
    stream << "              \"Pokrovskaya\": 2850\n";
    stream << "          },\n";
    stream << "          \"type\": \"Stop\"\n";
    stream << "      },\n";
    stream << "      {\n";
    stream << "          \"latitude\": 55.603601,\n";
    stream << "          \"longitude\": 37.635517,\n";
    stream << "          \"name\": \"Pokrovskaya\",\n";
    stream << "          \"road_distances\": {\n";
    stream << "              \"Rossoshanskaya ulitsa\": 3140\n";
    stream << "          },\n";
    stream << "          \"type\": \"Stop\"\n";
    stream << "      },\n";
    stream << "      {\n";
    stream << "          \"latitude\": 55.595579,\n";
    stream << "          \"longitude\": 37.605757,\n";
    stream << "          \"name\": \"Rossoshanskaya ulitsa\",\n";
    stream << "          \"road_distances\": {\n";
    stream << "              \"Pokrovskaya\": 3210\n";
    stream << "          },\n";
    stream << "          \"type\": \"Stop\"\n";
    stream << "      },\n";
    stream << "      {\n";
    stream << "          \"latitude\": 55.611717,\n";
    stream << "          \"longitude\": 37.603938,\n";
    stream << "          \"name\": \"Prazhskaya\",\n";
    stream << "          \"road_distances\": {\n";
    stream << "              \"Pokrovskaya\": 2260\n";
    stream << "          },\n";
    stream << "          \"type\": \"Stop\"\n";
    stream << "      },\n";
    stream << "      {\n";
    stream << "          \"is_roundtrip\": false,\n";
    stream << "          \"name\": \"750\",\n";
    stream << "          \"stops\": [\n";
    stream << "              \"Tolstopaltsevo\",\n";
    stream << "              \"Rasskazovka\"\n";
    stream << "          ],\n";
    stream << "          \"type\": \"Bus\"\n";
    stream << "      },\n";
    stream << "      {\n";
    stream << "          \"latitude\": 55.611087,\n";
    stream << "          \"longitude\": 37.20829,\n";
    stream << "          \"name\": \"Tolstopaltsevo\",\n";
    stream << "          \"road_distances\": {\n";
    stream << "              \"Rasskazovka\": 13800\n";
    stream << "          },\n";
    stream << "          \"type\": \"Stop\"\n";
    stream << "      },\n";
    stream << "      {\n";
    stream << "          \"latitude\": 55.632761,\n";
    stream << "          \"longitude\": 37.333324,\n";
    stream << "          \"name\": \"Rasskazovka\",\n";
    stream << "          \"road_distances\": {},\n";
    stream << "          \"type\": \"Stop\"\n";
    stream << "      }\n";
    stream << "  ],\n";
    stream << "  \"render_settings\": {\n";
    stream << "      \"bus_label_font_size\": 20,\n";
    stream << "      \"bus_label_offset\": [\n";
    stream << "          7,\n";
    stream << "          15\n";
    stream << "      ],\n";
    stream << "      \"color_palette\": [\n";
    stream << "          \"green\",\n";
    stream << "          [\n";
    stream << "              255,\n";
    stream << "              160,\n";
    stream << "              0\n";
    stream << "          ],\n";
    stream << "          \"red\"\n";
    stream << "      ],\n";
    stream << "      \"height\": 200,\n";
    stream << "      \"line_width\": 14,\n";
    stream << "      \"padding\": 30,\n";
    stream << "      \"stop_label_font_size\": 20,\n";
    stream << "      \"stop_label_offset\": [\n";
    stream << "          7,\n";
    stream << "          -3\n";
    stream << "      ],\n";
    stream << "      \"stop_radius\": 5,\n";
    stream << "      \"underlayer_color\": [\n";
    stream << "          255,\n";
    stream << "          255,\n";
    stream << "          255,\n";
    stream << "          0.85\n";
    stream << "      ],\n";
    stream << "      \"underlayer_width\": 3,\n";
    stream << "      \"width\": 200\n";
    stream << "  },\n";
    stream << "  \"routing_settings\": {\n";
    stream << "      \"bus_velocity\": 30,\n";
    stream << "      \"bus_wait_time\": 2\n";
    stream << "  },\n";
    stream << "  \"stat_requests\": [\n";
    stream << "      {\n";
    stream << "          \"id\": 1,\n";
    stream << "          \"name\": \"297\",\n";
    stream << "          \"type\": \"Bus\"\n";
    stream << "      },\n";
    stream << "      {\n";
    stream << "          \"id\": 2,\n";
    stream << "          \"name\": \"635\",\n";
    stream << "          \"type\": \"Bus\"\n";
    stream << "      },\n";
    stream << "      {\n";
    stream << "          \"id\": 3,\n";
    stream << "          \"name\": \"828\",\n";
    stream << "          \"type\": \"Bus\"\n";
    stream << "      },\n";
    stream << "      {\n";
    stream << "          \"id\": 4,\n";
    stream << "          \"name\": \"Universam\",\n";
    stream << "          \"type\": \"Stop\"\n";
    stream << "      },\n";
    stream << "      {\n";
    stream << "          \"from\": \"Biryulyovo Zapadnoye\",\n";
    stream << "          \"id\": 5,\n";
    stream << "          \"to\": \"Apteka\",\n";
    stream << "          \"type\": \"Route\"\n";
    stream << "      },\n";
    stream << "      {\n";
    stream << "          \"from\": \"Biryulyovo Zapadnoye\",\n";
    stream << "          \"id\": 6,\n";
    stream << "          \"to\": \"Pokrovskaya\",\n";
    stream << "          \"type\": \"Route\"\n";
    stream << "      },\n";
    stream << "      {\n";
    stream << "          \"from\": \"Biryulyovo Tovarnaya\",\n";
    stream << "          \"id\": 7,\n";
    stream << "          \"to\": \"Pokrovskaya\",\n";
    stream << "          \"type\": \"Route\"\n";
    stream << "      },\n";
    stream << "      {\n";
    stream << "          \"from\": \"Biryulyovo Tovarnaya\",\n";
    stream << "          \"id\": 8,\n";
    stream << "          \"to\": \"Biryulyovo Zapadnoye\",\n";
    stream << "          \"type\": \"Route\"\n";
    stream << "      },\n";
    stream << "      {\n";
    stream << "          \"from\": \"Biryulyovo Tovarnaya\",\n";
    stream << "          \"id\": 9,\n";
    stream << "          \"to\": \"Prazhskaya\",\n";
    stream << "          \"type\": \"Route\"\n";
    stream << "      },\n";
    stream << "      {\n";
    stream << "          \"from\": \"Apteka\",\n";
    stream << "          \"id\": 10,\n";
    stream << "          \"to\": \"Biryulyovo Tovarnaya\",\n";
    stream << "          \"type\": \"Route\"\n";
    stream << "      },\n";
    stream << "      {\n";
    stream << "          \"from\": \"Biryulyovo Zapadnoye\",\n";
    stream << "          \"id\": 11,\n";
    stream << "          \"to\": \"Tolstopaltsevo\",\n";
    stream << "          \"type\": \"Route\"\n";
    stream << "      }\n";
    stream << "  ]\n";
    stream << "}\n";
    return stream;
}

static std::stringstream Query3() {
    std::stringstream stream;
    stream << "{\n";
    stream << " \"base_requests\": [\n";
    stream << "     {\n";
    stream << "         \"is_roundtrip\": true,\n";
    stream << "         \"name\": \"289\",\n";
    stream << "         \"stops\": [\n";
    stream << "             \"Zagorye\",\n";
    stream << "             \"Lipetskaya ulitsa 46\",\n";
    stream << "             \"Lipetskaya ulitsa 40\",\n";
    stream << "             \"Lipetskaya ulitsa 40\",\n";
    stream << "             \"Lipetskaya ulitsa 46\",\n";
    stream << "             \"Moskvorechye\",\n";
    stream << "             \"Zagorye\"\n";
    stream << "         ],\n";
    stream << "         \"type\": \"Bus\"\n";
    stream << "     },\n";
    stream << "     {\n";
    stream << "         \"latitude\": 55.579909,\n";
    stream << "         \"longitude\": 37.68372,\n";
    stream << "         \"name\": \"Zagorye\",\n";
    stream << "         \"road_distances\": {\n";
    stream << "             \"Lipetskaya ulitsa 46\": 230\n";
    stream << "         },\n";
    stream << "         \"type\": \"Stop\"\n";
    stream << "     },\n";
    stream << "     {\n";
    stream << "         \"latitude\": 55.581441,\n";
    stream << "         \"longitude\": 37.682205,\n";
    stream << "         \"name\": \"Lipetskaya ulitsa 46\",\n";
    stream << "         \"road_distances\": {\n";
    stream << "             \"Lipetskaya ulitsa 40\": 390,\n";
    stream << "             \"Moskvorechye\": 12400\n";
    stream << "         },\n";
    stream << "         \"type\": \"Stop\"\n";
    stream << "     },\n";
    stream << "     {\n";
    stream << "         \"latitude\": 55.584496,\n";
    stream << "         \"longitude\": 37.679133,\n";
    stream << "         \"name\": \"Lipetskaya ulitsa 40\",\n";
    stream << "         \"road_distances\": {\n";
    stream << "             \"Lipetskaya ulitsa 40\": 1090,\n";
    stream << "             \"Lipetskaya ulitsa 46\": 380\n";
    stream << "         },\n";
    stream << "         \"type\": \"Stop\"\n";
    stream << "     },\n";
    stream << "     {\n";
    stream << "         \"latitude\": 55.638433,\n";
    stream << "         \"longitude\": 37.638433,\n";
    stream << "         \"name\": \"Moskvorechye\",\n";
    stream << "         \"road_distances\": {\n";
    stream << "             \"Zagorye\": 10000\n";
    stream << "         },\n";
    stream << "         \"type\": \"Stop\"\n";
    stream << "     }\n";
    stream << " ],\n";
    stream << " \"render_settings\": {\n";
    stream << "     \"bus_label_font_size\": 20,\n";
    stream << "     \"bus_label_offset\": [\n";
    stream << "         7,\n";
    stream << "         15\n";
    stream << "     ],\n";
    stream << "     \"color_palette\": [\n";
    stream << "         \"green\",\n";
    stream << "         [\n";
    stream << "             255,\n";
    stream << "             160,\n";
    stream << "             0\n";
    stream << "         ],\n";
    stream << "         \"red\"\n";
    stream << "     ],\n";
    stream << "     \"height\": 200,\n";
    stream << "     \"line_width\": 14,\n";
    stream << "     \"padding\": 30,\n";
    stream << "     \"stop_label_font_size\": 20,\n";
    stream << "     \"stop_label_offset\": [\n";
    stream << "         7,\n";
    stream << "         -3\n";
    stream << "     ],\n";
    stream << "     \"stop_radius\": 5,\n";
    stream << "     \"underlayer_color\": [\n";
    stream << "         255,\n";
    stream << "         255,\n";
    stream << "         255,\n";
    stream << "         0.85\n";
    stream << "     ],\n";
    stream << "     \"underlayer_width\": 3,\n";
    stream << "     \"width\": 200\n";
    stream << " },\n";
    stream << " \"routing_settings\": {\n";
    stream << "     \"bus_velocity\": 30,\n";
    stream << "     \"bus_wait_time\": 2\n";
    stream << " },\n";
    stream << " \"stat_requests\": [\n";
    stream << "     {\n";
    stream << "         \"id\": 1,\n";
    stream << "         \"name\": \"289\",\n";
    stream << "         \"type\": \"Bus\"\n";
    stream << "     },\n";
    stream << "     {\n";
    stream << "         \"from\": \"Zagorye\",\n";
    stream << "         \"id\": 2,\n";
    stream << "         \"to\": \"Moskvorechye\",\n";
    stream << "         \"type\": \"Route\"\n";
    stream << "     },\n";
    stream << "     {\n";
    stream << "         \"from\": \"Moskvorechye\",\n";
    stream << "         \"id\": 3,\n";
    stream << "         \"to\": \"Zagorye\",\n";
    stream << "         \"type\": \"Route\"\n";
    stream << "     },\n";
    stream << "     {\n";
    stream << "         \"from\": \"Lipetskaya ulitsa 40\",\n";
    stream << "         \"id\": 4,\n";
    stream << "         \"to\": \"Lipetskaya ulitsa 40\",\n";
    stream << "         \"type\": \"Route\"\n";
    stream << "     }\n";
    stream << " ]\n";
    stream << "}\n";
    return stream;
}

static std::stringstream Query4_make_base() {
    std::stringstream stream;

    stream << "{\n";
    stream << "    \"serialization_settings\": {\n";
    stream << "        \"file\": \"transport_catalogue.db\"\n";
    stream << "    },\n";
    stream << "    \"base_requests\": [\n";
    stream << "        {\n";
    stream << "            \"is_roundtrip\": true,\n";
    stream << "            \"name\": \"297\",\n";
    stream << "            \"stops\": [\n";
    stream << "                \"Biryulyovo Zapadnoye\",\n";
    stream << "                \"Biryulyovo Tovarnaya\",\n";
    stream << "                \"Universam\",\n";
    stream << "                \"Biryulyovo Zapadnoye\"\n";
    stream << "            ],\n";
    stream << "            \"type\": \"Bus\"\n";
    stream << "        },\n";
    stream << "        {\n";
    stream << "            \"is_roundtrip\": false,\n";
    stream << "            \"name\": \"635\",\n";
    stream << "            \"stops\": [\n";
    stream << "                \"Biryulyovo Tovarnaya\",\n";
    stream << "                \"Universam\",\n";
    stream << "                \"Prazhskaya\"\n";
    stream << "            ],\n";
    stream << "            \"type\": \"Bus\"\n";
    stream << "        },\n";
    stream << "        {\n";
    stream << "            \"latitude\": 55.574371,\n";
    stream << "            \"longitude\": 37.6517,\n";
    stream << "            \"name\": \"Biryulyovo Zapadnoye\",\n";
    stream << "            \"road_distances\": {\n";
    stream << "                \"Biryulyovo Tovarnaya\": 2600\n";
    stream << "            },\n";
    stream << "            \"type\": \"Stop\"\n";
    stream << "        },\n";
    stream << "        {\n";
    stream << "            \"latitude\": 55.587655,\n";
    stream << "            \"longitude\": 37.645687,\n";
    stream << "            \"name\": \"Universam\",\n";
    stream << "            \"road_distances\": {\n";
    stream << "                \"Biryulyovo Tovarnaya\": 1380,\n";
    stream << "                \"Biryulyovo Zapadnoye\": 2500,\n";
    stream << "                \"Prazhskaya\": 4650\n";
    stream << "            },\n";
    stream << "            \"type\": \"Stop\"\n";
    stream << "        },\n";
    stream << "        {\n";
    stream << "            \"latitude\": 55.592028,\n";
    stream << "            \"longitude\": 37.653656,\n";
    stream << "            \"name\": \"Biryulyovo Tovarnaya\",\n";
    stream << "            \"road_distances\": {\n";
    stream << "                \"Universam\": 890\n";
    stream << "            },\n";
    stream << "            \"type\": \"Stop\"\n";
    stream << "        },\n";
    stream << "        {\n";
    stream << "            \"latitude\": 55.611717,\n";
    stream << "            \"longitude\": 37.603938,\n";
    stream << "            \"name\": \"Prazhskaya\",\n";
    stream << "            \"road_distances\": {},\n";
    stream << "            \"type\": \"Stop\"\n";
    stream << "        }\n";
    stream << "    ],\n";
    stream << "    \"render_settings\": {\n";
    stream << "        \"bus_label_font_size\": 20,\n";
    stream << "        \"bus_label_offset\": [\n";
    stream << "            7,\n";
    stream << "            15\n";
    stream << "        ],\n";
    stream << "        \"color_palette\": [\n";
    stream << "            \"green\",\n";
    stream << "            [\n";
    stream << "                255,\n";
    stream << "                160,\n";
    stream << "                0\n";
    stream << "            ],\n";
    stream << "            \"red\"\n";
    stream << "        ],\n";
    stream << "        \"height\": 200,\n";
    stream << "        \"line_width\": 14,\n";
    stream << "        \"padding\": 30,\n";
    stream << "        \"stop_label_font_size\": 20,\n";
    stream << "        \"stop_label_offset\": [\n";
    stream << "            7,\n";
    stream << "            -3\n";
    stream << "        ],\n";
    stream << "        \"stop_radius\": 5,\n";
    stream << "        \"underlayer_color\": [\n";
    stream << "            255,\n";
    stream << "            255,\n";
    stream << "            255,\n";
    stream << "            0.85\n";
    stream << "        ],\n";
    stream << "        \"underlayer_width\": 3,\n";
    stream << "        \"width\": 200\n";
    stream << "    },\n";
    stream << "    \"routing_settings\": {\n";
    stream << "        \"bus_velocity\": 40,\n";
    stream << "        \"bus_wait_time\": 6\n";
    stream << "    }\n";
    stream << "}\n";

    return stream;
}

static std::stringstream Query4_process_requests() {
    std::stringstream stream;

    stream << "{\n";
    stream << "    \"serialization_settings\": {\n";
    stream << "        \"file\": \"transport_catalogue.db\"\n";
    stream << "    },\n";
    stream << "    \"stat_requests\": [\n";
    stream << "        {\n";
    stream << "            \"id\": 1,\n";
    stream << "            \"name\": \"297\",\n";
    stream << "            \"type\": \"Bus\"\n";
    stream << "        },\n";
    stream << "        {\n";
    stream << "            \"id\": 2,\n";
    stream << "            \"name\": \"635\",\n";
    stream << "            \"type\": \"Bus\"\n";
    stream << "        },\n";
    stream << "        {\n";
    stream << "            \"id\": 3,\n";
    stream << "            \"name\": \"Universam\",\n";
    stream << "            \"type\": \"Stop\"\n";
    stream << "        }\n";
    stream << "    ]\n";
    stream << "}\n";

    return stream;
}

#endif // TEST_QUERIES_H
